### ISSUE TITLE
Segfault when parsing libOpenCL.so on Power 9

### ISSUE THREAD

**Issue by mxz297** [dyninst/dyninst#1043]
It segfaulted even with 1 thread.  The binary is `/usr/local/cuda-11.0/targets/ppc64le-linux/lib/libOpenCL.so.1.0.0` on llnl.cs.rice.edu

**Comment by mxz297** [comment]
Stack trace:

```
(gdb) bt
#0  IndirectControlFlowAnalyzer::NewJumpTableAnalysis (this=0x7fffffffb230, outEdges=...) at /home/xm13/dyninst-master/dyninst/parseAPI/src/IndirectAnalyzer.C:89
#1  0x00007ffff79f21b4 in Dyninst::InsnAdapter::IA_IAPI::parseJumpTable (this=<optimized out>, currFunc=<error reading variable: value has been optimized out>, currBlk=<optimized out>, outEdges=...)
    at /home/xm13/dyninst-master/dyninst/parseAPI/src/IA_IAPI.C:918
#2  0x00007ffff79f7b64 in Dyninst::InsnAdapter::IA_IAPI::getNewEdges (this=0x101b4130, outEdges=..., context=0x10183ba0, currBlk=0x1016f930, num_insns=<optimized out>, plt_entries=<optimized out>, knownTargets=...)
    at /home/xm13/dyninst-master/dyninst/parseAPI/src/IA_IAPI.C:716
#3  0x00007ffff799e01c in Dyninst::ParseAPI::Parser::ProcessCFInsn (this=0x10171770, frame=..., cur=0x1016f930, ah=0x101b4130) at /home/xm13/dyninst-master/dyninst/parseAPI/src/ParserDetails.C:415
#4  0x00007ffff79b3a04 in Dyninst::ParseAPI::Parser::parse_frame_one_iteration (this=0x10171770, frame=..., recursive=true) at /home/xm13/dyninst-master/dyninst/parseAPI/src/ParserDetails.h:251
#5  0x00007ffff79b5198 in Dyninst::ParseAPI::Parser::parse_frame (this=0x10171770, frame=..., recursive=true) at /home/xm13/dyninst-master/dyninst/parseAPI/src/Parser.C:1378
#6  0x00007ffff79b566c in Dyninst::ParseAPI::Parser::ProcessOneFrame (this=0x10171770, pf=0x101a1e40, recursive=<optimized out>) at /home/xm13/dyninst-master/dyninst/parseAPI/src/Parser.C:455
#7  0x00007ffff79b5778 in Dyninst::ParseAPI::Parser::SpawnProcessFrame (this=0x10171770, pf=<optimized out>, recursive=<optimized out>) at /home/xm13/dyninst-master/dyninst/parseAPI/src/Parser.C:632
#8  0x00007ffff7246828 in GOMP_task (fn=0x7ffff79b57b0 <Dyninst::ParseAPI::Parser::_ZN7Dyninst8ParseAPI6Parser10LaunchWorkEP17LockFreeQueueItemIPNS0_10ParseFrameEEb._omp_fn.1(void)>, data=<optimized out>, cpyfn=0x0, arg_size=24, 
    arg_align=8, if_clause=<optimized out>, flags=<optimized out>, depend=0x0, priority=0) at /tmp/xm13/spack-stage/spack-stage-gcc-8.3.0-vki5t4bqfrtb3yy3rob5wn7f4dcaz4q6/spack-src/libgomp/task.c:352
#9  0x00007ffff79a4e40 in Dyninst::ParseAPI::Parser::LaunchWork (this=0x10171770, frame_list=<optimized out>, recursive=<optimized out>) at /home/xm13/dyninst-master/dyninst/parseAPI/src/Parser.C:619
#10 0x00007ffff7246828 in GOMP_task (fn=0x7ffff79b57b0 <Dyninst::ParseAPI::Parser::_ZN7Dyninst8ParseAPI6Parser10LaunchWorkEP17LockFreeQueueItemIPNS0_10ParseFrameEEb._omp_fn.1(void)>, data=<optimized out>, cpyfn=0x0, arg_size=24, 
    arg_align=8, if_clause=<optimized out>, flags=<optimized out>, depend=0x0, priority=0) at /tmp/xm13/spack-stage/spack-stage-gcc-8.3.0-vki5t4bqfrtb3yy3rob5wn7f4dcaz4q6/spack-src/libgomp/task.c:352
#11 0x00007ffff79a4e40 in Dyninst::ParseAPI::Parser::LaunchWork (this=0x10171770, frame_list=<optimized out>, recursive=<optimized out>) at /home/xm13/dyninst-master/dyninst/parseAPI/src/Parser.C:619
#12 0x00007ffff7240ec4 in GOMP_parallel (fn=0x7ffff79a4ea0 <Dyninst::ParseAPI::Parser::_ZN7Dyninst8ParseAPI6Parser13ProcessFramesEP13LockFreeQueueIPNS0_10ParseFrameEEb._omp_fn.2(void)>, data=0x7fffffffc130, num_threads=1, 
    flags=<optimized out>) at /tmp/xm13/spack-stage/spack-stage-gcc-8.3.0-vki5t4bqfrtb3yy3rob5wn7f4dcaz4q6/spack-src/libgomp/parallel.c:168
#13 0x00007ffff79ab680 in ProcessFrames (recursive=true, work_queue=0x7fffffffc290, this=0x10171770) at /home/xm13/dyninst-master/dyninst/parseAPI/src/Parser.C:668
#14 Dyninst::ParseAPI::Parser::parse_frames (this=0x10171770, work=..., recursive=true) at /home/xm13/dyninst-master/dyninst/parseAPI/src/Parser.C:668
#15 0x00007ffff79ac750 in Dyninst::ParseAPI::Parser::parse_vanilla (this=0x10171770) at /home/xm13/dyninst-master/dyninst/parseAPI/src/Parser.C:331
#16 0x00007ffff79acb24 in Dyninst::ParseAPI::Parser::parse (this=0x10171770) at /home/xm13/dyninst-master/dyninst/parseAPI/src/Parser.C:180
#17 0x00007ffff79d8634 in Dyninst::ParseAPI::CodeObject::parse (this=0x10173dd0) at /home/xm13/dyninst-master/dyninst/parseAPI/src/CodeObject.C:186
#18 0x00007ffff79d8810 in Dyninst::ParseAPI::CodeObject::CodeObject (this=0x10173dd0, cs=<optimized out>, fact=<optimized out>, cb=0x0, defMode=<optimized out>, ignoreParse=<optimized out>)
    at /home/xm13/dyninst-master/dyninst/parseAPI/src/CodeObject.C:80
#19 0x0000000010009178 in main (argc=4, argv=0x7fffffffcc98) at openmp-loops.cpp:721
```

**Comment by mxz297** [comment]
This turns out to be a x86-64 binary. We still have one #ifdefine in instruction that disabled implicit operand decoding for x86 instructions on non-x86 architectures.
