### ISSUE TITLE
Assertion error when handling AArch64 binary: tried to access system register not accessible in EL0

### ISSUE THREAD

**Issue by bin2415** [dyninst/dyninst#1186]
**Intention**
Disassemble the AArch64 binary.

**Describe the bug**
When I use dyninst to disassemble aarch64 binary which is striped, it incurs an assertion: `instructionAPI/src/aarch64_opcode_tables.C:3839: static Dyninst::MachRegister Dyninst::InstructionAPI::InstructionDecoder_aarch64::sysRegMap(unsigned int): Assertion !"tried to access system register not accessible in EL0"' failed.`

**To Reproduce**
The code I used to disassemble:

```c++
#include <stdio.h>
#include <sstream>
#include <fstream>
#include <set>
#include <cstdint>

#include "CodeObject.h"
#include "Function.h"
#include "Symtab.h"
#include "Instruction.h"
int main(int argc, char** argv){
    auto symtab_cs = std::make_shared<ParseAPI::SymtabCodeSource>(argv[0]);
    CHECK(symtab_cs) << "Error during creation of ParseAPI::SymtabCodeSource!";
    auto code_obj = std::make_shared<ParseAPI::CodeObject>(symtab_cs.get());
    CHECK(code_obj) << "Error during creation of ParseAPI::CodeObject";
    code_obj->parse();
    auto idiom = Dyninst::ParseAPI::GapParsingType::IdiomMatching;
    for (auto &reg: symtab_cs->regions()) {
         code_obj->parseGaps(reg, idiom);
   }
}
```

The version I used is the v12.0.0: https://github.com/dyninst/dyninst/tree/v12.0.0

The used binary is [strip.zip](https://github.com/dyninst/dyninst/files/7880481/strip.zip)

**System (please complete the following information):**
 - What platform x86_64, ubuntu 20.04
 - What commit? https://github.com/dyninst/dyninst/tree/v12.0.0

**Comment by bin2415** [comment]
Hello, thanks for your prompt reply. My source code has some mistakes which leads to could not reproduce this error. I update the source code and it is reproducible on my machine now. By the way, I set `DYNINST_DEBUG_PARSE=1` environment, but it do not have output. It seems that it never call the function `parsing_printf_int` before crash.

**Comment by hainest** [comment]
Bah! I don't know how I didn't see the `argv[0]` in the example. Thanks for the updated test!

I can now confirm this crashes when running Dyninst built on Ubuntu 20.04 x86_64. It does not crash when using Ubuntu 20.04 aarch64. This is a problem with cross-platform instruction decoding.

>By the way, I set DYNINST_DEBUG_PARSE=1 environment, but it do not have output. It seems that it never call the function parsing_printf_int before crash.

I was seeing the same.

gdb backtrace:

    #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
    #1  0x00007ffff778d859 in __GI_abort () at abort.c:79
    #2  0x00007ffff778d729 in __assert_fail_base (fmt=0x7ffff7923588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
        assertion=0x7ffff7705e98 "!\"tried to access system register not accessible in EL0\"", 
        file=0x7ffff7705e40 "dyninst/src/instructionAPI/src/aarch64_opcode_tables.C", line=3839, function=<optimized out>)
        at assert.c:92
    #3  0x00007ffff779ef36 in __GI___assert_fail (assertion=0x7ffff7705e98 "!\"tried to access system register not accessible in EL0\"", 
        file=0x7ffff7705e40 "dyninst/src/instructionAPI/src/aarch64_opcode_tables.C", line=3839, 
        function=0x7ffff7705dd0 "static Dyninst::MachRegister Dyninst::InstructionAPI::InstructionDecoder_aarch64::sysRegMap(unsigned int)") at assert.c:101
    #4  0x00007ffff76dc00f in Dyninst::InstructionAPI::InstructionDecoder_aarch64::sysRegMap (m=m@entry=56457)
        at dyninst/src/instructionAPI/src/aarch64_opcode_tables.C:3839
    #5  0x00007ffff76dd8a0 in Dyninst::InstructionAPI::InstructionDecoder_aarch64::processSystemInsn (this=0x55555568c1d0)
        at dyninst/src/instructionAPI/src/InstructionDecoder-aarch64.C:391
    #6  0x00007ffff76dfdff in Dyninst::InstructionAPI::InstructionDecoder_aarch64::decodeOperands (this=0x55555568c1d0, insn_to_complete=<optimized out>)
        at dyninst/src/instructionAPI/src/InstructionDecoder-aarch64.C:2978
    #7  0x00007ffff76dff46 in Dyninst::InstructionAPI::InstructionDecoder_aarch64::doDelayedDecode (this=0x55555568c1d0, insn_to_complete=0x7fffffffbac0)
        at /var/software/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-11.1.0/boost-1.73.0-qrc5nfnchhb7v7mgmupejmoj7vzn2ktq/include/boost/smart_ptr/shared_ptr.hpp:746
    #8  0x00007ffff7615968 in Dyninst::InstructionAPI::Instruction::decodeOperands (this=0x7fffffffbac0)
        at dyninst/src/instructionAPI/src/Instruction.C:122
    #9  0x00007ffff76180ea in Dyninst::InstructionAPI::Instruction::getOperands (this=this@entry=0x7fffffffbac0, operands=std::vector of length 0, capacity 0)
        at dyninst/src/instructionAPI/src/Instruction.C:231
    #10 0x00007ffff7ce0559 in hd::ProbabilityCalculator::decodeInstruction (this=0x7fffffffbac0, data=..., addr=4250722)
        at dyninst/src/parseAPI/src/ProbabilisticParser.C:507
    #11 0x00007ffff7ce0b00 in hd::ProbabilityCalculator::calcForwardWeights (valid=@0x7fffffffbd2f: true, tree=<optimized out>, addr=4250722, cur=0, 
        this=0x7fffffffbdc0) at dyninst/src/parseAPI/src/ProbabilisticParser.C:416
    #12 hd::ProbabilityCalculator::calcForwardWeights (this=0x7fffffffbdc0, cur=0, addr=4250722, tree=0x7fffffffbdc8, valid=@0x7fffffffbd2f: true)
        at dyninst/src/parseAPI/src/ProbabilisticParser.C:404
    #13 0x00007ffff7ce1266 in hd::ProbabilityCalculator::calcProbByMatchingIdioms (this=this@entry=0x7fffffffbdc0, addr=<optimized out>, addr@entry=4250722)
        at dyninst/src/parseAPI/src/ProbabilisticParser.h:147
    #14 0x00007ffff7c6527c in Dyninst::ParseAPI::Parser::probabilistic_gap_parsing (this=0x5555556773e0, cr=0x5555556364f0)
        at dyninst/src/parseAPI/src/Parser-speculative.C:383
    #15 0x0000555555558928 in main ()
