### ISSUE TITLE
Assertion failure in DwarfWalker

### ISSUE THREAD

**Issue by morehouse** [dyninst/dyninst#152]
On master, while instrumenting some SPEC CPU2006 binaries with stack diversification, the following assertion fails:
`performStackMods: /p/paradyn/development/mm/githead/tmp/dyninst/symtabAPI/src/dwarfWalker.C:740: bool Dyninst::SymtabAPI::DwarfWalker::parseCommonBlock(): Assertion '!"No common block variables to parse!"' failed.`

Full backtrace:
```
#0  0x0000003193032625 in raise () from /lib64/libc.so.6
#1  0x0000003193033e05 in abort () from /lib64/libc.so.6
#2  0x000000319302b74e in __assert_fail_base () from /lib64/libc.so.6
#3  0x000000319302b810 in __assert_fail () from /lib64/libc.so.6
#4  0x00007f5c0494f359 in Dyninst::SymtabAPI::DwarfWalker::parseCommonBlock (
    this=0x7ffc1c349a40)
    at /p/paradyn/development/mm/githead/tmp/dyninst/symtabAPI/src/dwarfWalker.C:740
#5  0x00007f5c04953aa8 in Dyninst::SymtabAPI::DwarfWalker::parse_int (
    this=0x7ffc1c349a40, e=0x2125438, p=true)
    at /p/paradyn/development/mm/githead/tmp/dyninst/symtabAPI/src/dwarfWalker.C:328
#6  0x00007f5c04953c92 in Dyninst::SymtabAPI::DwarfWalker::parse_int (
    this=0x7ffc1c349a40, e=<value optimized out>, p=true)
    at /p/paradyn/development/mm/githead/tmp/dyninst/symtabAPI/src/dwarfWalker.C:412
#7  0x00007f5c04953c92 in Dyninst::SymtabAPI::DwarfWalker::parse_int (
    this=0x7ffc1c349a40, e=<value optimized out>, p=true)
    at /p/paradyn/development/mm/githead/tmp/dyninst/symtabAPI/src/dwarfWalker.C:412
#8  0x00007f5c049547e2 in Dyninst::SymtabAPI::DwarfWalker::parseModule (
    this=0x7ffc1c349a40, is_info=<value optimized out>, 
    fixUnknownMod=@0x7ffc1c3499e8)
    at /p/paradyn/development/mm/githead/tmp/dyninst/symtabAPI/src/dwarfWalker.C:239
#9  0x00007f5c04954a37 in Dyninst::SymtabAPI::DwarfWalker::parse (
    this=0x7ffc1c349a40)
    at /p/paradyn/development/mm/githead/tmp/dyninst/symtabAPI/src/dwarfWalker.C:143
#10 0x00007f5c049038d4 in Dyninst::SymtabAPI::Object::fix_global_symbol_modules_static_dwarf (this=0x1f12470)
    at /p/paradyn/development/mm/githead/tmp/dyninst/symtabAPI/src/Object-elf.C:2438
#11 0x00007f5c04905402 in Dyninst::SymtabAPI::Object::load_object (
    this=0x1f12470, alloc_syms=<value optimized out>)
    at /p/paradyn/development/mm/githead/tmp/dyninst/symtabAPI/src/Object-elf.C:1603
#12 0x00007f5c049061b5 in Dyninst::SymtabAPI::Object::Object (this=0x1f12470, 
    mf_=0x1f107f0, err_func=<value optimized out>, alloc_syms=true)
    at /p/paradyn/development/mm/githead/tmp/dyninst/symtabAPI/src/Object-elf.C:2844
#13 0x00007f5c048c3c9d in Dyninst::SymtabAPI::Symtab::Symtab (this=0x1f114b0, 
    filename="", defensive_bin=false, err=@0x7ffc1c34a01f)
    at /p/paradyn/development/mm/githead/tmp/dyninst/symtabAPI/src/Symtab.C:1305
#14 0x00007f5c048c434c in Dyninst::SymtabAPI::Symtab::openFile (
    obj=@0x1f112d0, filename="481.wrf/run/build_peak_stackDiv.0000/wrf-orig", 
    def_binary=Dyninst::SymtabAPI::Symtab::NotDefensive)
    at /p/paradyn/development/mm/githead/tmp/dyninst/symtabAPI/src/Symtab.C:2152
#15 0x00007f5c05247ef4 in image::image (this=0x1f11210, desc=..., 
    err=@0x7ffc1c34a1bf, mode=BPatch_normalMode, 
    parseGaps=<value optimized out>)
    at /p/paradyn/development/mm/githead/tmp/dyninst/dyninstAPI/src/image.C:1425
#16 0x00007f5c05248b32 in image::parseImage (desc=..., mode=BPatch_normalMode, 
    parseGaps=true)
    at /p/paradyn/development/mm/githead/tmp/dyninst/dyninstAPI/src/image.C:1230
#17 0x00007f5c0525c6a9 in mapped_object::createMappedObject (desc=..., p=
    0x1f10e50, analysisMode=BPatch_normalMode, parseGaps=true)
    at /p/paradyn/development/mm/githead/tmp/dyninst/dyninstAPI/src/mapped_object.C:154
#18 0x00007f5c05238d54 in BinaryEdit::openFile (file=
    "481.wrf/run/build_peak_stackDiv.0000/wrf-orig", mgr=..., patch=0x0, 
    member=<value optimized out>)
    at /p/paradyn/development/mm/githead/tmp/dyninst/dyninstAPI/src/binaryEdit.C:339
#19 0x00007f5c051f9230 in BPatch_binaryEdit::BPatch_binaryEdit (
    this=0x1f10760, 
    path=0x1f0de98 "481.wrf/run/build_peak_stackDiv.0000/wrf-orig", 
    openDependencies=true)
    at /p/paradyn/development/mm/githead/tmp/dyninst/dyninstAPI/src/BPatch_binaryEdit.C:90
#20 0x00007f5c051b153d in BPatch::openBinary (this=<value optimized out>, 
    path=0x1f0de98 "481.wrf/run/build_peak_stackDiv.0000/wrf-orig", 
    openDependencies=true)
    at /p/paradyn/development/mm/githead/tmp/dyninst/dyninstAPI/src/BPatch.C:1879
#21 0x0000000000403480 in main (argc=8, argv=0x7ffc1c34a958)
    at performStackMods.C:252
```

**Comment by jdetter** [comment]
Is this something you would need me or Bill to do or are you working on this?

**Comment by wrwilliams** [comment]
Assert is safe to remove, returning false is fine.
