### ISSUE TITLE
Segfault at exit of the profiled program when trying Tau with Dyninst 12.3.0 on IBM64

### ISSUE THREAD

**Issue by LucasVlk** [dyninst/dyninst#1556]
**Intention**
I've tried to use Tau (https://github.com/UO-OACISS/tau2) with Dyninst 12.3.0 on the Typhon machine (uoregon-OACISS)

**Describe the bug**
When I launch tau_run with Dyninst on a program, it crashes at the exit of the profiled program with a segmentation fault.
I've used gdb on a hello_world program to quickly check:

```bash
gdb --args tau_run -T serial,dyn ~/hello_world/hello_world_typhon
(gdb) b dyninst-12.3.0-working/dyninstAPI/src/Relocation/Transformers/Instrumenter.C:373
(gdb) r
```

```bash
Thread 1 "tau_run" hit Breakpoint 1, Dyninst::Relocation::Instrumenter::handleCondDirExits (this=this@entry=0x7ffffffd5210, trace=trace@entry=0x182b9800, cfg=cfg@entry=0x1823c870, exit=exit@entry=0x182f3420)
    at dyninst-12.3.0-working/dyninstAPI/src/Relocation/Transformers/Instrumenter.C:373
373	   cfg->makeEdge(new Target<RelocBlock *>(instRelocBlock),
(gdb) s
Dyninst::Relocation::TargetInt::TargetInt (this=0x182c77c0) at /home/users/lucas_vlk/tau2_typhon/dyninst-12.3.0-working/dyninstAPI/src/Relocation/Transformers/../CFG/RelocTarget.h:110
110	  Target(RelocBlock * t) : t_(t) { assert(t_); }
(gdb) s

Thread 1 "tau_run" received signal SIGSEGV, Segmentation fault.
0x00007ffff7e93b78 in Dyninst::Relocation::Instrumenter::handleCondDirExits (this=this@entry=0x7ffffffd5210, trace=trace@entry=0x182b9800, cfg=cfg@entry=0x1823c870, exit=exit@entry=0x182f3420)
    at dyninst-12.3.0-working/dyninstAPI/src/Relocation/Transformers/../CFG/RelocTarget.h:110
110	  Target(RelocBlock * t) : t_(t) { assert(t_); }
```

**To Reproduce**
To reproduce the error with tau on Typhon
```bash
ssh orthus.nic.uoregon.edu; ssh typhon
```

Download tau:
```bash
git clone https://github.com/UO-OACISS/tau2.git
cd tau2
```

Replace the tau2/configure file with the one I'm attaching to this report 
[configure.zip](https://github.com/dyninst/dyninst/files/12786668/configure.zip). 
I also put it in at /tmp/configure in Typhon to make it easier:
```bash
cp /tmp/configure configure
```
This configure file will install Dyninst 12.3.0 with dependencies and libraries needed by tau.

Then install tau with Dyninst (it will take some time):
```bash
./configure -tag=dyn -bfd=download -dyninst=download
make install
```

Then configure PATH, LD_LIBRARY_PATH and DYNINSTAPI_RT_LIB:
```bash
export TAU2_ROOT=$PWD  # <Your tau2 directory>
export PATH=$TAU2_ROOT/ibm64linux/bin:$PATH
export LD_LIBRARY_PATH=$TAU2_ROOT/ibm64linux/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$TAU2_ROOT/ibm64linux/dyninst-12.3.0-working/lib:$LD_LIBRARY_PATH
export DYNINSTAPI_RT_LIB=$TAU2_ROOT/ibm64linux/dyninst-12.3.0-working/lib/libdyninstAPI_RT.so
```

Then we can launch tau with Dyninst on some examples tau, but the bug is raised when running tau_run:
```bash
cd $TAU2_ROOT/examples/dyninst/
make
tau_run -T serial,dyn -o klargest.i klargest
tau_exec -T serial,dyn ./klargest.i
pprof -a
```

**Expected behavior**
tau_run should load libTAUsh-dyn-tbb.so and create an instrumented binary from the executable, so we can profile it with tau_exec.

**System (please complete the following information):**
 - What platform? IBM64 (4.18.0-425.3.1.el8.ppc64le)
 - What commit/tag? Dyninst v12.3.0 https://github.com/dyninst/dyninst/releases/tag/v12.3.0
 - Maybe libc version : ldd (GNU libc) 2.28
 - gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18)

**Additional context**
This bug does not occur on the x86-64 and craycnl machines I tried (Saturn and Roberta).
I've tried a couple of examples from https://github.com/dyninst/examples (CFGraph, codeCoverage, disassemble) without any issue.

**Comment by hainest** [comment]
Confirmed. Thanks for the detailed report!


[tau.rhel8.ppc64.klargest.tar.gz](https://github.com/dyninst/dyninst/files/12788090/tau.rhel8.ppc64.klargest.tar.gz)

----

### Backtrace
```terminal
Thread 1 "tau_run" received signal SIGSEGV, Segmentation fault.
0x00007ffff7e8d5f0 in Dyninst::Relocation::Instrumenter::handleCondDirExits (this=<optimized out>, trace=0x13cd65b0, cfg=0x11d26150, exit=<optimized out>)
    at /home/users/thaines/workspace/typhon/tau2/dyninst-12.3.0-working/dyninstAPI/src/Relocation/Transformers/../CFG/RelocTarget.h:110
110	  Target(RelocBlock * t) : t_(t) { assert(t_); }
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-225.el8.ppc64le libgcc-8.5.0-18.el8.ppc64le libgomp-8.5.0-18.el8.ppc64le libstdc++-8.5.0-18.el8.ppc64le libzstd-1.4.4-1.el8.ppc64le xz-libs-5.2.4-4.el8_6.ppc64le zlib-1.2.11-21.el8_7.ppc64le
(gdb) bt
#0  0x00007ffff7e8d5f0 in Dyninst::Relocation::Instrumenter::handleCondDirExits (this=<optimized out>, trace=0x13cd65b0, cfg=0x11d26150, 
    exit=<optimized out>) at /home/users/thaines/workspace/typhon/tau2/dyninst-12.3.0-working/dyninstAPI/src/Relocation/Transformers/../CFG/RelocTarget.h:110
#1  0x00007ffff7e8e854 in Dyninst::Relocation::Instrumenter::funcExitInstrumentation (this=this@entry=0x7ffffffcd030, trace=trace@entry=0x13cd65b0, 
    cfg=cfg@entry=0x11d26150) at /home/users/thaines/workspace/typhon/tau2/dyninst-12.3.0-working/dyninstAPI/src/Relocation/Transformers/Instrumenter.C:256
#2  0x00007ffff7e8eabc in Dyninst::Relocation::Instrumenter::process (cfg=0x11d26150, trace=0x13cd65b0, this=0x7ffffffcd030)
    at /home/users/thaines/workspace/typhon/tau2/dyninst-12.3.0-working/dyninstAPI/src/Relocation/Transformers/Instrumenter.C:89
#3  Dyninst::Relocation::Instrumenter::process (this=0x7ffffffcd030, trace=0x13cd65b0, cfg=0x11d26150)
    at /home/users/thaines/workspace/typhon/tau2/dyninst-12.3.0-working/dyninstAPI/src/Relocation/Transformers/Instrumenter.C:49
#4  0x00007ffff7e8a70c in Dyninst::Relocation::Transformer::processGraph (this=0x7ffffffcd030, cfg=0x11d26150)
    at /home/users/thaines/workspace/typhon/tau2/dyninst-12.3.0-working/dyninstAPI/src/Relocation/Transformers/Transformer.C:43
#5  0x00007ffff7e6dc80 in Dyninst::Relocation::CodeMover::transform (this=0x10d8d090, t=...)
    at /home/users/thaines/workspace/typhon/tau2/dyninst-12.3.0-working/dyninstAPI/src/Relocation/CodeMover.C:138
#6  0x00007ffff7ddf4fc in AddressSpace::transform (this=this@entry=0x10143d90, cm=...)
    at /home/users/thaines/workspace/typhon/tau2/ibm64linux/boost_1_79_0/boost/smart_ptr/shared_ptr.hpp:784
#7  0x00007ffff7ddf9b8 in AddressSpace::relocateInt (this=this@entry=0x10143d90, begin=..., end=end@entry=0x12, nearTo=268439416)
    at /home/users/thaines/workspace/typhon/tau2/ibm64linux/boost_1_79_0/boost/smart_ptr/detail/sp_counted_base_gcc_atomic.hpp:108
#8  0x00007ffff7de061c in AddressSpace::relocate (this=0x10143d90) at /usr/include/c++/8/bits/stl_tree.h:995
#9  0x00007ffff7eabdb8 in Dyninst::PatchAPI::DynInstrumenter::run (this=<optimized out>)
    at /home/users/thaines/workspace/typhon/tau2/dyninst-12.3.0-working/dyninstAPI/src/Relocation/DynInstrumenter.C:54
#10 0x00007ffff6aae358 in Dyninst::PatchAPI::Patcher::run (this=0x10194860)
    at /home/users/thaines/workspace/typhon/tau2/dyninst-12.3.0-working/patchAPI/src/Command.C:113
#11 0x00007ffff6aad3d8 in Dyninst::PatchAPI::Command::commit (this=<optimized out>)
    at /home/users/thaines/workspace/typhon/tau2/dyninst-12.3.0-working/patchAPI/src/Command.C:54
#12 0x00007ffff7dd6e34 in AddressSpace::patch (as=<optimized out>)
    at /home/users/thaines/workspace/typhon/tau2/ibm64linux/boost_1_79_0/boost/smart_ptr/shared_ptr.hpp:784
#13 0x00007ffff7d9f438 in BPatch_binaryEdit::writeFile (this=0x101401e0, outFile=0x7ffffffcd7b8 "klargest.i")
    at /home/users/thaines/workspace/typhon/tau2/dyninst-12.3.0-working/dyninstAPI/src/BPatch_binaryEdit.C:214
#14 0x0000000010009540 in tauRewriteBinary(BPatch*, char const*, char*, char*, char*, char*, char*) ()
#15 0x000000001000a43c in main ()
```
