### ISSUE TITLE
aarch64 stackwalking needs work.

### ISSUE THREAD

**Issue by bigtrak** [dyninst/dyninst#1677]
Running the dyninst testsuite on aarch64 (arm64) experiences failures
that result in core dumps.

The most noticeable is that several tests with stackwalk involved blow
out the call stack.  

One issue is that there may be a dwarf parsing issue which appears
to succeed, but returns info that causes the recursion.   From examining
Sasha's work on adding additional steppers to stackwalking, there may be
a problem evaluating DWARF expressions that are needed for stackwalking.
His work-in-progress workspace is available in AFS and on zeroah for
reference.

When someone has the time to look at this, I would recommend checking
Sasha's work out, as it could be  dwarf error and/or a need for additional
stackwalk steppers.   

One thing to do is go back to about dyninst V10 on ubuntu 18 or even 16 (try a container)
and see if the problems exist there.  IIRC, Sasha was concerned that a tool chain change
(such as different DWARF) may be part of the issue, or perhaps some other dyninst change
caused these errors to occur.   

This problem has been ongoing for some time, nobody has had the time to look at it so far.

**Comment by hainest** [comment]
Reported by Sameer Shende at Univ of Oregon.

Two Grace-Hopper and Grace-Grace systems running on RHEL 8.8 on aarch64 (80 core ARM processor).

```
(gdb) run -T cupti ./mm -o mm.i
Starting program: /tmpdir/vi-hps/opt/packages/tau/2.33.1-gcc-openmpi-gpu/arm64_linux/bin/tau_run -T cupti ./mm -o mm.i

./mm> Loading libTAUsh-papi-mpi-pthread-python-cupti-pdt.so ...

Thread 1 "tau_run" received signal SIGSEGV, Segmentation fault.
0x00004000009ba07c in dwarf_tag (die=0xfffffffcad18, tag=0x0, error=<optimized out>) at dwarf_query.c:205
205	dwarf_query.c: No such file or directory.
Missing separate debuginfos, use: yum debuginfo-install elfutils-libelf-0.188-3.el8.aarch64 glibc-2.28-225.el8_8.6.aarch64 zlib-1.2.11-21.el8_7.aarch64
(gdb) where 
#0  0x00004000009ba07c in dwarf_tag (die=0xfffffffcad18, tag=0x0, error=<optimized out>)
    at dwarf_query.c:205
#1  0x00004000008f3e74 in Dyninst::SymtabAPI::Object::fix_global_symbol_modules_static_dwarf() ()
   from /tmpdir/vi-hps/opt/packages/e4s/23.11/openmpi/spack/opt/spack/linux-rhel8-aarch64/gcc-11.2.0/dyninst-12.3.0-t4r4ws7ea5yj6iya6vphrtahxknhfnnz/lib/libsymtabAPI.so.12.3
#2  0x00004000008f5664 in Dyninst::SymtabAPI::Object::load_object(bool) ()
   from /tmpdir/vi-hps/opt/packages/e4s/23.11/openmpi/spack/opt/spack/linux-rhel8-aarch64/gcc-11.2.0/dyninst-12.3.0-t4r4ws7ea5yj6iya6vphrtahxknhfnnz/lib/libsymtabAPI.so.12.3
#3  0x00004000008f5d34 in Dyninst::SymtabAPI::Object::Object(MappedFile*, bool, void (*)(char const*), bool, Dyninst::SymtabAPI::Symtab*) ()
   from /tmpdir/vi-hps/opt/packages/e4s/23.11/openmpi/spack/opt/spack/linux-rhel8-aarch64/gcc-11.2.0/dyninst-12.3.0-t4r4ws7ea5yj6iya6vphrtahxknhfnnz/lib/libsymtabAPI.so.12.3
#4  0x00004000008b1848 in Dyninst::SymtabAPI::Symtab::Symtab(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool&) ()
   from /tmpdir/vi-hps/opt/packages/e4s/23.11/openmpi/spack/opt/spack/linux-rhel8-aarch64/gcc-11.2.0/dyninst-12.3.0-t4r4ws7ea5yj6iya6vphrtahxknhfnnz/lib/libsymtabAPI.so.12.3
#5  0x00004000008b1c74 in Dyninst::SymtabAPI::Symtab::openFile(Dyninst::SymtabAPI::Symtab*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Dyninst::SymtabAPI::Symtab::def_t) ()
   from /tmpdir/vi-hps/opt/packages/e4s/23.11/openmpi/spack/opt/spack/linux-rhel8-aarch64/gcc-11.2.0/dyninst-12.3.0-t4r4ws7ea5yj6iya6vphrtahxknhfnnz/lib/libsymtabAPI.so.12.3
#6  0x000040000015fe30 in image::image(fileDescriptor&, bool&, BPatch_hybridMode, bool) ()
   from /tmpdir/vi-hps/opt/packages/e4s/23.11/openmpi/spack/opt/spack/linux-rhel8-aarch64/gcc-11.2.0/dyninst-12.3.0-t4r4ws7ea5yj6iya6vphrtahxknhfnnz/lib/libdyninstAPI.so.12.3
#7  0x0000400000160bd0 in image::parseImage(fileDescriptor&, BPatch_hybridMode, bool) ()
   from /tmpdir/vi-hps/opt/packages/e4s/23.11/openmpi/spack/opt/spack/linux-rhel8-aarch64/gcc-11.2.0/dyninst-12.3.0-t4r4ws7ea5yj6iya6vphrtahxknhfnnz/lib/libdyninstAPI.so.12.3
#8  0x000040000016a568 in mapped_object::createMappedObject(fileDescriptor&, AddressSpace*, BPatch_hybridMode, bool) ()
   from /tmpdir/vi-hps/opt/packages/e4s/23.11/openmpi/spack/opt/spack/linux-rhel8-aarch64/gcc-11.2.0/dyninst-12.3.0-t4r4ws7ea5yj6iya6vphrtahxknhfnnz/lib/libdyninstAPI.so.12.3
#9  0x0000400000153630 in BinaryEdit::openFile(std::__cxx11::basic_string<char, std::char_traits<char>, st--Type <RET> for more, q to quit, c to continue without paging--c
d::allocator<char> > const&, boost::shared_ptr<Dyninst::PatchAPI::PatchMgr>, boost::shared_ptr<Dyninst::PatchAPI::Patcher>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /tmpdir/vi-hps/opt/packages/e4s/23.11/openmpi/spack/opt/spack/linux-rhel8-aarch64/gcc-11.2.0/dyninst-12.3.0-t4r4ws7ea5yj6iya6vphrtahxknhfnnz/lib/libdyninstAPI.so.12.3
#10 0x0000400000116464 in BPatch_binaryEdit::BPatch_binaryEdit(char const*, bool) () from /tmpdir/vi-hps/opt/packages/e4s/23.11/openmpi/spack/opt/spack/linux-rhel8-aarch64/gcc-11.2.0/dyninst-12.3.0-t4r4ws7ea5yj6iya6vphrtahxknhfnnz/lib/libdyninstAPI.so.12.3
#11 0x00004000000d6870 in BPatch::openBinary(char const*, bool) () from /tmpdir/vi-hps/opt/packages/e4s/23.11/openmpi/spack/opt/spack/linux-rhel8-aarch64/gcc-11.2.0/dyninst-12.3.0-t4r4ws7ea5yj6iya6vphrtahxknhfnnz/lib/libdyninstAPI.so.12.3
#12 0x0000000000408ec0 in tauRewriteBinary (bpatch=0x504890, mutateeName=mutateeName@entry=0xfffffffd4410 "./mm", outfile=outfile@entry=0xfffffffd4810 "mm.i", libname=libname@entry=0xfffffffdd010 "libTAUsh-papi-mpi-pthread-python-cupti-pdt.so", staticlibname=staticlibname@entry=0xfffffffe5010 "libtau-papi-mpi-pthread-python-cupti-pdt.a", staticmpilibname=staticmpilibname@entry=0xfffffffed010 "libTauMpi-papi-mpi-pthread-python-cupti-pdt.a", bindings=bindings@entry=0x50f2d0 "-papi-mpi-pthread-python-cupti-pdt") at /tmpdir/vi-hps/opt/packages/tau/SRC/tau2/utils/error_code.hpp:964
#13 0x0000000000405afc in main (argc=<optimized out>, argv=0xffffffffd138) at /tmpdir/vi-hps/opt/packages/tau/SRC/tau2/utils/error_code.hpp:1367

```
