### ISSUE TITLE
processCreate crashed on aarch64

### ISSUE THREAD

**Issue by wangzhijun2005** [dyninst/dyninst#449]
Platform: aarch64:Linux:4.1.12:#46 SMP PREEMPT, CentOS

yum install elfutils-devel
# rpm -qa|grep elf
elfutils-libelf-devel-0.163-3.h1.aarch64
elfutils-0.163-3.h1.aarch64
elfutils-devel-0.163-3.h1.aarch64
elfutils-libelf-0.163-3.h1.aarch64
elfutils-libs-0.163-3.h1.aarch64

Pull the code from arm64/feature/relocation branch, turn on all the debug options of dyninst in debug.h,  then build dyninstAPI.

Test case 1:  Use the test program in https://github.com/dyninst/dyninst/issues/436, then run : 
export LD_LIBRARY_PATH=/usr/local/lib
export DYNINSTAPI_RT_LIB=/usr/local/lib/libdyninstAPI_RT.so
# ./test /usr/bin/echo 1
DYNINSTAPI_RT_LIB=/usr/local/lib/libdyninstAPI_RT.so
Creating process /usr/bin/echo in directory 
Arguments: (2)
   0: /usr/bin/echo
   1: 1
Environment: (0)
[281473411620864]dynProcess.C[85]: stdin: 0, stdout: 1, stderr: 2
[281473411620864]unix.C[353]: Candidate RTLib is /usr/local/lib/libdyninstAPI_RT.so
[281473411620864]unix.C[353]: Candidate RTLib is /usr/local/lib/libdyninstAPI_RT.so
[281473411620864]unix.C[353]: Candidate RTLib is /usr/local/lib/libdyninstAPI_RT.so
Created process 17343
[281473411620864]dynProcess.C[348]: attempting to bootstrap process 17343
[281473411620864]Processing initial shared objects
[281473411620864]----
[281473411620864]mapped_object.C[151]:  about to parseImage
[281473411620864]mapped_object.C[153]: name /usr/bin/echo, codeBase 0x0, dataBase 0x0
[281473411620864]image.C[1220]:  about to create image
[281473411620864]image.C[1415]:  opening file /usr/bin/echo
[281473411620864]image.C[1506]:  before findMain
[281473411620864]image.C[1513]: findMain analysis succeeded.
[281473411620864]image.C[1544]:  before determineImageType
New variable, mangled program_name, module echo...
New variable, mangled quote_quoting_options, module echo...
New variable, mangled exit_failure, module echo...
New variable, mangled Version, module echo...
New variable, mangled version_etc_copyright, module echo...
[281473411620864]image.C[1222]:  created image
[281473411620864]image.C[1227]: processing executable object
[281473411620864]mapped_object.C[200]:  creating mapped object
[281473411620864][mapped_object.C:105] Creating new mapped_object /usr/bin/echo/
[281473411620864][mapped_object.C:107]  codeBase 0x0, codeOffset 0x400000, size 24444
[281473411620864][mapped_object.C:109]  dataBase 0x0, dataOffset 0x41fd38, size 1232
[281473411620864][mapped_object.C:111]  fileDescriptor: code at 0x0, data 0x0
[281473411620864][mapped_object.C:113]  Code: 0x400000 to 0x405f7c
[281473411620864][mapped_object.C:115]  Data: 0x41fd38 to 0x420208
[281473411620864]mapped_object.C[205]:  leaving createMappedObject(/usr/bin/echo)
[281473411620864]dynProcess.C[724]: findSignalhandler(0x34cf220)
[281473411620864]dynProcess.C[730]: findSignalhandler(0x34cf220): gettingSymbolInfo
[281473411620864]dynProcess.C[741]: leaving findSignalhandler(0x34cf220)
[281473411620864]dynProcess.C[670]: adding shared object echo, addr range 0x0 to 0x5f7c
Adding shared object echo, addr range 0x0 to 0x5f7c
[281473411620864]Begin getDyninstRTLibName
[281473411620864]unix.C[322]: Candidate RTLib is /usr/local/lib/libdyninstAPI_RT.so
[281473411620864]unix.C[322]: Candidate RTLib is /usr/local/lib/libdyninstAPI_RT.so
[281473411620864]unix.C[322]: Candidate RTLib is /usr/local/lib/libdyninstAPI_RT.so
[281473411620864]dynProcess.C[601]:  leave setAOut/setting main
Library: /usr/lib64/ld-2.17.so / ffffaa746000, <lib>
[281473411620864]mapped_object.C[151]:  about to parseImage
[281473411620864]mapped_object.C[153]: name /usr/lib64/ld-2.17.so, codeBase 0xffffaa746000, dataBase 0xffffaa746000
[281473411620864]image.C[1220]:  about to create image
[281473411620864]image.C[1415]:  opening file /usr/lib64/ld-2.17.so
[281473411620864]image.C[1506]:  before findMain
[281473411620864]image.C[1513]: findMain analysis succeeded.
[281473411620864]image.C[1544]:  before determineImageType
New variable, mangled library_path, module ld-2.17.so...
New variable, mangled preload_file.11592, module ld-2.17.so...
New variable, mangled debopts.11741, module ld-2.17.so...
New variable, mangled unsecure_envvars.11798, module ld-2.17.so...
New variable, mangled audit_iface_names.11568, module ld-2.17.so...
New variable, mangled any_debug, module ld-2.17.so...
New variable, mangled version_info, module ld-2.17.so...
New variable, mangled preloadlist, module ld-2.17.so...
New variable, mangled dyn_temp.11382, module ld-2.17.so...
New variable, mangled data.11355, module ld-2.17.so...
New variable, mangled tls_init_tp_called, module ld-2.17.so...
New variable, mangled audit_list, module ld-2.17.so...
New variable, mangled _dl_rtld_libname, module ld-2.17.so...
New variable, mangled _dl_rtld_libname2, module ld-2.17.so...
New variable, mangled newname.11536, module ld-2.17.so...
New variable, mangled curwd.11128, module ld-2.17.so...
New variable, mangled expected.11330, module ld-2.17.so...
New variable, mangled dummy_bucket.11458, module ld-2.17.so...
New variable, mangled system_dirs, module ld-2.17.so...
New variable, mangled expected2.11329, module ld-2.17.so...
New variable, mangled expected_note.11336, module ld-2.17.so...
New variable, mangled ncapstr, module ld-2.17.so...
New variable, mangled max_capstrlen, module ld-2.17.so...
New variable, mangled capstr, module ld-2.17.so...
New variable, mangled rtld_search_dirs, module ld-2.17.so...
New variable, mangled env_path_list, module ld-2.17.so...
New variable, mangled max_dirnamelen, module ld-2.17.so...
New variable, mangled undefined_msg, module ld-2.17.so...
New variable, mangled errstring.11054, module ld-2.17.so...
New variable, mangled msg.11060, module ld-2.17.so...
New variable, mangled dl_close_state.11111, module ld-2.17.so...
New variable, mangled _dl_out_of_memory, module ld-2.17.so...
New variable, mangled receiver, module ld-2.17.so...
New variable, mangled primes.10087, module ld-2.17.so...
New variable, mangled running, module ld-2.17.so...
New variable, mangled lowpc, module ld-2.17.so...
New variable, mangled textsize, module ld-2.17.so...
New variable, mangled log_hashfraction, module ld-2.17.so...
New variable, mangled fromlimit, module ld-2.17.so...
New variable, mangled narcsp, module ld-2.17.so...
New variable, mangled data, module ld-2.17.so...
New variable, mangled tos, module ld-2.17.so...
New variable, mangled froms, module ld-2.17.so...
New variable, mangled fromidx, module ld-2.17.so...
New variable, mangled narcs, module ld-2.17.so...
New variable, mangled expected1.8859, module ld-2.17.so...
New variable, mangled expected2.8860, module ld-2.17.so...
New variable, mangled expected3.8861, module ld-2.17.so...
New variable, mangled expected4.8862, module ld-2.17.so...
New variable, mangled cache, module ld-2.17.so...
New variable, mangled cachesize, module ld-2.17.so...
New variable, mangled cache_new, module ld-2.17.so...
New variable, mangled auxvars.11115, module ld-2.17.so...
New variable, mangled expected_note.11131, module ld-2.17.so...
New variable, mangled alloc_end, module ld-2.17.so...
New variable, mangled alloc_ptr, module ld-2.17.so...
New variable, mangled alloc_last_block, module ld-2.17.so...
New variable, mangled pc_offset, module ld-2.17.so...
New variable, mangled pc_scale, module ld-2.17.so...
New variable, mangled nsamples, module ld-2.17.so...
New variable, mangled samples, module ld-2.17.so...
New variable, mangled _GLOBAL_OFFSET_TABLE_, module ld-2.17.so...
New variable, mangled __curbrk, module ld-2.17.so...
New variable, mangled __libc_multiple_libcs, module ld-2.17.so...
New variable, mangled __GI__itoa_lower_digits, module ld-2.17.so...
New variable, mangled _DYNAMIC, module ld-2.17.so...
New variable, mangled __libc_enable_secure_internal, module ld-2.17.so...
New variable, mangled _environ, module ld-2.17.so...
New variable, mangled __GI___libc_stack_end, module ld-2.17.so...
New variable, mangled _dl_skip_args, module ld-2.17.so...
New variable, mangled _rtld_local, module ld-2.17.so...
New variable, mangled _dl_argc, module ld-2.17.so...
New variable, mangled _dl_argv_internal, module ld-2.17.so...
New variable, mangled _dl_random, module ld-2.17.so...
New variable, mangled _rtld_local_ro, module ld-2.17.so...
New variable, mangled _dl_starting_up_internal, module ld-2.17.so...
New variable, mangled __stack_prot, module ld-2.17.so...
New variable, mangled rtld_errno, module ld-2.17.so...
New variable, mangled __pointer_chk_guard_local, module ld-2.17.so...
New variable, mangled audit_list_string, module ld-2.17.so...
New variable, mangled __stack_chk_guard, module ld-2.17.so...
New variable, mangled GLIBC_PRIVATE, module ld-2.17.so...
New variable, mangled _r_debug, module ld-2.17.so...
[281473411620864]image.C[1222]:  created image
[281473411620864]image.C[1225]: processing shared object
[281473411620864]mapped_object.C[200]:  creating mapped object
[281473411620864][mapped_object.C:105] Creating new mapped_object /usr/lib64/ld-2.17.so/
[281473411620864][mapped_object.C:107]  codeBase 0xffffaa746000, codeOffset 0x0, size 122296
[281473411620864][mapped_object.C:109]  dataBase 0xffffaa746000, dataOffset 0x2fba0, size 5208
[281473411620864][mapped_object.C:111]  fileDescriptor: code at 0xffffaa746000, data 0xffffaa746000
[281473411620864][mapped_object.C:113]  Code: 0xffffaa746000 to 0xffffaa763db8
[281473411620864][mapped_object.C:115]  Data: 0xffffaa775ba0 to 0xffffaa776ff8
[281473411620864]mapped_object.C[205]:  leaving createMappedObject(/usr/lib64/ld-2.17.so)
[281473411620864]dynProcess.C[724]: findSignalhandler(0x34fd2c0)
[281473411620864]dynProcess.C[730]: findSignalhandler(0x34fd2c0): gettingSymbolInfo
[281473411620864]dynProcess.C[741]: leaving findSignalhandler(0x34fd2c0)
[281473411620864]dynProcess.C[670]: adding shared object ld-2.17.so, addr range 0xffffaa746000 to 0xffffaa763db8
Adding shared object ld-2.17.so, addr range 0xaa746000 to 0xaa763db8
[281473411620864]----
[281473411620864]dynProcess.C[1474]: added thread 17343 to process 17343
[281473411620864]Stackwalker stepper 0x34fdae0 is a DyninstDynamicStepper
[281473411620864]Stackwalker stepper 0x34fdc10 is a FrameFuncStepper
[281473411620864][unix.C:510] - hasPassedMain returning 0 (ffffaa746cc0 ffffaa746cc0)
[281473411620864]dynProcess.C[378]: inserting breakpoint at main
[281473411620864]dynProcess.C[938]: main function not yet found, cannot insert breakpoint
[281473411620864]dynProcess.C[381]: bootstrap failed while setting a breakpoint at main
Failed to bootstrap process 17343: terminating...
[281473411620864]dynProcess.C[1034]: Terminating process 17343
[281473411620864]pcEventMuxer.C[223]: Begin callbackMux, process pointer = 0x34ab010, event post-ForceTerminate
[281473411620864]pcEventMuxer.C[438]: Added event post-ForceTerminate to mailbox, size now 1
[281473411620864]pcEventMuxer.C[225]: after muxing event, mailbox size is 1
[281473411620864]pcEventMuxer.C[463]: Returning event post-ForceTerminate from mailbox
[281473411620864]pcEventHandler.C[66]: attempting to handle event post-ForceTerminate on thread 17343/17343
[281473411620864]pcEventHandler.C[191]: continue condition ( 1 0 1 1 0 1 )
[281473411620864]pcEventHandler.C[227]: delaying process continue: <return success> <desired stop> <stopped> <no reported event> <terminated> <no pending events>
[281473411620864]pcEventHandler.C[233]: pending exit reported to BPatch-level, marking process exited
[281473411620864]pcEventHandler.C[239]: finished handling event: post-ForceTerminate (err = false)
[281473411620864]dynProcess.C[1042]: finished terminating process 17343
[281473411620864]dynProcess.C[280]: destructing PCProcess 17343
--FATAL-- #68: Dyninst was unable to create the specified process
--FATAL-- #68: create process failed bootstrap
app (nil)

Test case 2: create userapp.c, then run 
-------------------------------
#include <stdio.h>
int main(int argc, char *argv[]) {
   int a=10;
   int b=20;
   printf("%d",a+b);
   return 0;
}
-------------------------------

# ./test ./userapp
DYNINSTAPI_RT_LIB=/usr/local/lib/libdyninstAPI_RT.so
Creating process ./userapp in directory 
Arguments: (1)
   0: ./userapp
Environment: (0)
[281472861626368]dynProcess.C[85]: stdin: 0, stdout: 1, stderr: 2
Segmentation fault (core dumped)

# gdb ./test core.18626
GNU gdb (GDB) Red Hat Enterprise Linux 7.12-21.h1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./test...done.
[New LWP 18626]
[New LWP 18627]
Trying host libthread_db library: libthread_db.so.1.
Host libthread_db.so.1 resolved to: /lib64/libthread_db.so.1.
Found 0 new threads in iteration 0.
Warning: thread_db_find_new_threads_silently: Cannot find new threads: debugger service failed
Warning: couldn't activate thread debugging using libthread_db: Cannot find new threads: debugger service failed
Trying host libthread_db library: /lib64/libthread_db.so.1.
Found 0 new threads in iteration 0.
Warning: thread_db_find_new_threads_silently: Cannot find new threads: debugger service failed
Warning: couldn't activate thread debugging using libthread_db: Cannot find new threads: debugger service failed
thread_db_load_search returning 0

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Trying host libthread_db library: libthread_db.so.1.
Host libthread_db.so.1 resolved to: /lib64/libthread_db.so.1.
Found 0 new threads in iteration 0.
Warning: thread_db_find_new_threads_silently: Cannot find new threads: debugger service failed
Warning: couldn't activate thread debugging using libthread_db: Cannot find new threads: debugger service failed
Trying host libthread_db library: /lib64/libthread_db.so.1.
Found 0 new threads in iteration 0.
Warning: thread_db_find_new_threads_silently: Cannot find new threads: debugger service failed
Warning: couldn't activate thread debugging using libthread_db: Cannot find new threads: debugger service failed
thread_db_load_search returning 0

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Core was generated by `./test ./userapp'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000ffff81c95418 in _dwarf_error () from /usr/local/lib/libdwarf.so
[Current thread is 1 (LWP 18626)]
Missing separate debuginfos, use: debuginfo-install boost-atomic-1.53.0-25.aarch64 boost-chrono-1.53.0-25.aarch64 boost-date-time-1.53.0-25.aarch64 boost-system-1.53.0-25.aarch64 boost-thread-1.53.0-25.aarch64 bzip2-libs-1.0.6-13.aarch64 elfutils-libelf-0.163-3.h1.aarch64 elfutils-libs-0.163-3.h1.aarch64 glibc-2.17-196.h20.aarch64 libgcc-4.9.3-199192.h1.aarch64 libstdc++-4.9.3-199192.h1.aarch64 xz-libs-5.1.2-12alpha.aarch64 zlib-1.2.7-15.aarch64
(gdb) bt
#0  0x0000ffff81c95418 in _dwarf_error () from /usr/local/lib/libdwarf.so
#1  0x0000ffff81ca58d4 in dwarf_dieoffset () from /usr/local/lib/libdwarf.so
#2  0x0000ffff812172f8 in Dyninst::SymtabAPI::Object::dwarf_parse_aranges (this=0xffffc7ac8248, this@entry=0x27514120, dbg=dbg@entry=0x27521930, dies_seen=std::set with 0 elements)
    at /root/dyninst-arm64-feature-relocation/symtabAPI/src/Object-elf.C:2467
#3  0x0000ffff81217748 in Dyninst::SymtabAPI::Object::fix_global_symbol_modules_static_dwarf (this=this@entry=0x27514120) at /root/dyninst-arm64-feature-relocation/symtabAPI/src/Object-elf.C:2496
#4  0x0000ffff8121a2d8 in Dyninst::SymtabAPI::Object::load_object (this=this@entry=0x27514120, alloc_syms=alloc_syms@entry=112) at /root/dyninst-arm64-feature-relocation/symtabAPI/src/Object-elf.C:1611
#5  0x0000ffff8121af80 in Dyninst::SymtabAPI::Object::Object (this=0x27514120, mf_=0x275133b0, err_func=<optimized out>, alloc_syms=112, st=<optimized out>) at /root/dyninst-arm64-feature-relocation/symtabAPI/src/Object-elf.C:2974
#6  0x0000ffff811de530 in Dyninst::SymtabAPI::Symtab::Symtab (this=0x27513180, filename="", defensive_bin=255, err=@0xffffc7ac85f8: 120) at /root/dyninst-arm64-feature-relocation/symtabAPI/src/Symtab.C:1261
#7  0x0000ffff811de904 in Dyninst::SymtabAPI::Symtab::openFile (obj=@0xffffc7ac8580: 0x0, filename=<error reading variable: Cannot access memory at address 0x2750f860>, 
    def_binary=def_binary@entry=Dyninst::SymtabAPI::Symtab::NotDefensive) at /root/dyninst-arm64-feature-relocation/symtabAPI/src/Symtab.C:2077
#8  0x0000ffff81e4620c in PCProcess::setEnvPreload (envp=std::vector of length 0, capacity 0, fileName=<error reading variable: Cannot access memory at address 0x2750f860>)
    at /root/dyninst-arm64-feature-relocation/dyninstAPI/src/unix.C:334
#9  0x0000ffff81ded2e4 in PCProcess::createProcess (file=<error reading variable: Cannot access memory at address 0x2750f860>, argv=std::vector of length 1, capacity 1 = {...}, analysisMode=analysisMode@entry=BPatch_normalMode, 
    envp=std::vector of length 0, capacity 0, dir="", stdin_fd=stdin_fd@entry=0, stdout_fd=stdout_fd@entry=1, stderr_fd=stderr_fd@entry=2) at /root/dyninst-arm64-feature-relocation/dyninstAPI/src/dynProcess.C:95
#10 0x0000ffff81d4fd70 in BPatch_process::BPatch_process (this=0x275109e0, path=0xffffc7ac9787 "./userapp", argv=<optimized out>, mode=BPatch_normalMode, envp=<optimized out>, stdin_fd=0, stdout_fd=1, stderr_fd=2)
    at /root/dyninst-arm64-feature-relocation/dyninstAPI/src/BPatch_process.C:189
#11 0x0000ffff81d304d4 in BPatch::processCreate (this=<optimized out>, path=<optimized out>, argv=0xffffc7ac9350, envp=0x5ac4f882, stdin_fd=0, stdout_fd=24, stderr_fd=0, mode=4096)
    at /root/dyninst-arm64-feature-relocation/dyninstAPI/src/BPatch.C:1198
#12 0x0000000000400d64 in main (argc=2, argv=0xffffc7ac9350) at test.c:29
(gdb) 

BTW, I have run the test smoothly on Ubuntu 16.04 on X86 platform using the master branch.
$ dpkg -l|grep elf
ii  libelf1:amd64                                0.165-3ubuntu1                                        amd64        library to read and write ELF files

**Comment by mxz297** [comment]
Instrumentation on ARM is currently under development
