### ISSUE TITLE
Incorrect instrumentation in libc

### ISSUE THREAD

**Issue by hainest** [dyninst/dyninst#762]
This is a combination of #753 and #761 using master(952dae51a).

On ulna.llnl.gov (ARM/ThunderX2) using gcc-8.3.1, glibc-2.17, and RHEL 7.6, I get

	$ export OMP_NUM_THREADS=2
	$ export DYNINSTAPI_RT_LIB=$(pwd)/../dyninst/lib/libdyninstAPI_RT.so
	$ export my_ld_paths=$(pwd):$(pwd)/../dyninst/lib:$LD_LIBRARY_PATH
	$ LD_LIBRARY_PATH=$my_ld_paths DYNINST_REWRITER_NO_UNLINK=1 ./test_driver -64 -rewriter -g++ -dynamiclink -nonpic -test test_reloc -log tmp.log

		TEST                       COMP   OPT  ABI MODE     THREAD  LINK    PIC     RESULT
		test_reloc                 g++    none 64  rewriter NA      dynamic nonPIC  CRASHED (Group Teardown)

	$ cd binaries
	$ gdb --args rewritten_test_reloc.dyn_g++_64_none_none_13050000 -run test_reloc
	$ set env LD_LIBRARY_PATHS=.:...

	Program received signal SIGSEGV, Segmentation fault.
	0x0040505400000000 in ?? ()
	Missing separate debuginfos, use: debuginfo-install libgcc-4.8.5-37.el7_6.aarch64 libstdc++-4.8.5-37.el7_6.aarch64
	(gdb) bt
	#0  0x0040505400000000 in ?? ()
	#1  0x00004000002f1578 in __libc_start_main (main=0x4024f41403f7fd, argc=3, argv=0xffffffffa208, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
			stack_end=<optimized out>) at libc-start.c:225
	#2  0x0000000000500040 in ?? ()
	#3  0x0000ffffffffa74f in ?? ()
	#4  0x41505f4544554c43 in ?? ()
	Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Here are the re-written binaries. [ulna.tar.gz](https://github.com/dyninst/dyninst/files/4709327/ulna.tar.gz)

---

On quartz.llnl.gov (x86_64) using 8.1.0, glibc-2.17, and RHEL 7.8, I get

	$ export OMP_NUM_THREADS=2
	$ export DYNINSTAPI_RT_LIB=$(pwd)/../dyninst/lib/libdyninstAPI_RT.so
	$ export my_ld_paths=$(pwd):$(pwd)/../dyninst/lib:$LD_LIBRARY_PATH
	$ LD_LIBRARY_PATH=$my_ld_paths DYNINST_REWRITER_NO_UNLINK=1 ./test_driver -64 -rewriter -g++ -dynamiclink -nonpic -test test_reloc -log tmp.log

		TEST                       COMP   OPT  ABI MODE     THREAD  LINK    PIC     RESULT
		test_reloc                 g++    none 64  rewriter NA      dynamic nonPIC  CRASHED (Group Teardown)

	$ cd binaries
	$ gdb --args rewritten_test_reloc.dyn_g++_64_none_none_22500000 -run test_reloc
	$ set env LD_LIBRARY_PATHS=.:...

	Program received signal SIGILL, Illegal instruction.
	0x00002aaaab198a41 in ?? ()
	(gdb) bt
	#0  0x00002aaaab198a41 in ?? ()
	#1  0x0000000000437604 in ?? ()
	#2  0x00000000006ee0c0 in ?? ()
	#3  0x131e9a395f43c500 in ?? ()
	#4  0x00000000006ee0c0 in ?? ()
	#5  0x00007fffffff9f1e in ?? ()
	#6  0x00007fffffff9f26 in ?? ()
	#7  0x0000000000000000 in ?? ()

Here are the re-written binaries. [quartz.tar.gz](https://github.com/dyninst/dyninst/files/4709328/quartz.tar.gz)

**Comment by hainest** [comment]
This is now causing hangs on lassen (https://bottle.cs.wisc.edu/details/1387). This is very recent behavior and I'm not sure why it manifested. I've been having trouble getting the runs to complete there for about a week. I finally cranked the allocation time to 5 hours to get it to finish.

**Comment by hainest** [comment]
This can now be debugged since https://github.com/dyninst/dyninst/pull/963 allows using SIGILL to debug trampolines where this bug lies.
