### ISSUE TITLE
amd64_7_arg_call passing, then segfaulting from shared pointer on VEX

### ISSUE THREAD

**Issue by jdetter** [dyninst/dyninst#90]
The `amd64_7_arg_call` test passes, but then somehow gets a segfault when releasing a libboost shared pointer. I ran into this with boost version 1.58.

```
TEST                       COMP   OPT  ABI MODE     THREAD  LINK    PIC     RESULT
amd64_7_arg_call           g++    none 64  create   NA      dynamic nonPIC  PASSED

Thread 1 "test_driver" received signal SIGSEGV, Segmentation fault.
0x00007ffff625d974 in fclose@@GLIBC_2.2.5 () from /lib64/libc.so.6
(gdb) info stack
#0  0x00007ffff625d974 in fclose@@GLIBC_2.2.5 () from /lib64/libc.so.6
#1  0x00007ffff5b7f6d9 in boost::detail::sp_counted_impl_pd<_IO_FILE*, int (*)(_IO_FILE*)>::dispose (this=0x7bf4b930) at /usr/include/boost/smart_ptr/detail/sp_counted_impl.hpp:153
#2  0x00007ffff59319d0 in boost::detail::sp_counted_base::release (this=0x7bf4b930)
    at /usr/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp:146
#3  0x00007ffff5931a63 in boost::detail::shared_count::~shared_count (this=0x7fffffffcdd8,
    __in_chrg=<optimized out>) at /usr/include/boost/smart_ptr/detail/shared_count.hpp:443
#4  0x00007ffff5b7f472 in boost::shared_ptr<_IO_FILE>::~shared_ptr (this=0x7fffffffcdd0,
    __in_chrg=<optimized out>) at /usr/include/boost/smart_ptr/shared_ptr.hpp:323
#5  0x00007ffff5b7ee8e in BinaryEdit::getResolvedLibraryPath (filename="libstdc++.so.6",
    paths=std::vector of length 2, capacity 2 = {...})
    at /home/detter/Workspace/dyninst/dyninstAPI/src/linux.C:222
#6  0x00007ffff5b83310 in BinaryEdit::openResolvedLibraryName (this=0xc642760,
    filename="libstdc++.so.6", retMap=std::map with 0 elements)
    at /home/detter/Workspace/dyninst/dyninstAPI/src/unix.C:530
#7  0x00007ffff5a123ec in BinaryEdit::getAllDependencies (this=0xc642760,
    deps=std::map with 1 elements = {...})
    at /home/detter/Workspace/dyninst/dyninstAPI/src/binaryEdit.C:470
#8  0x00007ffff59a16c4 in BPatch_binaryEdit::BPatch_binaryEdit (this=0xbc7e7b0,
    path=0xaaa638 "amd64_7_arg_call.dyn_g++_64_none_none", openDependencies=true)
    at /home/detter/Workspace/dyninst/dyninstAPI/src/BPatch_binaryEdit.C:101
#9  0x00007ffff590d316 in BPatch::openBinary (this=0x184ca60,
    path=0xaaa638 "amd64_7_arg_call.dyn_g++_64_none_none", openDependencies=true)
    at /home/detter/Workspace/dyninst/dyninstAPI/src/BPatch.C:1879
#10 0x00007ffff5fcd969 in DyninstComponent::group_setup(RunGroup*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Parameter*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Parameter*> > >&) () from /usr/local/bin/testsuite/libtestdyninst.so
#11 0x0000000000417fd2 in executeGroup(RunGroup*, std::vector<RunGroup*, std::allocator<RunGroup*> >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Parameter*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Parameter*> > >&) ()
#12 0x000000000041909a in startAllTests(std::vector<RunGroup*, std::allocator<RunGroup*> >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Parameter*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Parameter*> > >&) ()
#13 0x0000000000419cdb in main ()
```

**Comment by jdetter** [comment]
This does not affect the master branch.

**Comment by jdetter** [comment]
@mxz297 It appears that before 015ce98dc4be967b87d89692f6b0e3eae0ac55d4 we pass these tests, however afterwards we don't pass the tests. Could you take a look at this after you're done with #80?

**Comment by jdetter** [comment]
@mxz297 you were right, recompiling the testsuite resolved these issues. I will do a full run to see if we are passing the entire testsuite.
