### ISSUE TITLE
Crash in __libdw_find_attr() when processing DWARF

### ISSUE THREAD

**Issue by woodard** [dyninst/dyninst#903]
When processing the symtab for /lib64/libQt5MultimediaWidgets.so.5.15.1 from qt5-qtmultimedia-5.15.1-1.fc33.x86_64
with dyninst trunk at commit 4311e94817bf60dffb557c4ffffd19bc04b7df3f
run with OMP_NUM_THREADS=1
using this test code
[repo1.C.gz](https://github.com/dyninst/dyninst/files/5461783/repo1.C.gz)

I get the following crash:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7721e24 in __libdw_find_attr (die=0x7fffffffb8e0, search_name=3, codep=0x7fffffffb890, formp=0x7fffffffb894) at libdwP.h:681
681	      if (unlikely (die->cu == NULL
#0  0x00007ffff7721e24 in __libdw_find_attr (die=0x7fffffffb8e0, search_name=3, codep=0x7fffffffb890, formp=0x7fffffffb894) at libdwP.h:681
#1  0x00007ffff77203bb in dwarf_attr (die=0x7fffffffb8e0, search_name=3, result=0x7fffffffb890) at dwarf_attr.c:45
#2  0x00007ffff7721a4f in dwarf_attr_integrate (die=0x7fffffffb8e0, search_name=3, result=0x7fffffffb890) at dwarf_attr_integrate.c:44
#3  0x00007ffff77202e1 in dwarf_diename (die=<optimized out>) at dwarf_diename.c:43
#4  0x00007ffff7f75a6b in Dyninst::SymtabAPI::DwarfWalker::findDieName (name="", die=...) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:1462
#5  Dyninst::SymtabAPI::DwarfWalker::findName (this=0x7fffffffbf30, name="") at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:1474
#6  0x00007ffff7f793b1 in Dyninst::SymtabAPI::DwarfWalker::parseFormalParam (this=0x7fffffffbf30) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.h:276
#7  0x00007ffff7f7f4d8 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf30, e=..., p=true) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:367
#8  0x00007ffff7f7f6e1 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf30, e=..., p=true) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:444
#9  0x00007ffff7f7f6e1 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf30, e=..., p=true) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:444
#10 0x00007ffff7f7f6e1 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf30, e=..., p=true) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:444
#11 0x00007ffff7f7f99c in Dyninst::SymtabAPI::DwarfWalker::parseModule (this=0x7fffffffbf30, moduleDIE=..., fixUnknownMod=@0x7fffffffbf18: 0x4c8890) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:259
#12 0x00007ffff7f7fd28 in Dyninst::SymtabAPI::DwarfWalker::_ZN7Dyninst9SymtabAPI11DwarfWalker5parseEv._omp_fn.0(void) () at /usr/include/c++/10/bits/stl_vector.h:1043
#13 0x00007ffff75c8d36 in GOMP_parallel (fn=0x7ffff7f7fc00 <Dyninst::SymtabAPI::DwarfWalker::_ZN7Dyninst9SymtabAPI11DwarfWalker5parseEv._omp_fn.0(void)>, data=0x7fffffffc820, num_threads=1, flags=0) at ../../../libgomp/parallel.c:171
#14 0x00007ffff7f7c27e in Dyninst::SymtabAPI::DwarfWalker::parse (this=0x7fffffffc880) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:162
#15 0x00007ffff7f2de31 in Dyninst::SymtabAPI::Object::parseTypeInfo (this=0x480bb0) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/Object-elf.C:4495
#16 0x00007ffff7eda4d9 in Dyninst::SymtabAPI::Symtab::parseTypes (this=0x468780) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/Symtab.C:2164
#17 0x00007ffff7ecc448 in Dyninst::SymtabAPI::FunctionBase::getParams (this=0x52c440, params_=std::vector of length 0, capacity 0) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/Function.C:122
#18 0x000000000040356b in main (argc=<optimized out>, argv=<optimized out>) at repo1.C:64
```

Other libraries that have the same problem:
/lib64/libQt5QuickTest.so.5.15.1 from qt5-qtdeclarative-5.15.1-1.fc33.x86_64
/lib64/libTKRWMesh.so.7.4.0
/lib64/libTKMesh.so.7.4.0 from opencascade-modeling-7.4.0-5.fc33.x86_64
/lib64/libTKStd.so.7.4.0 from opencascade-ocaf-7.4.0-5.fc33.x86_64

**Comment by woodard** [comment]
Verified that this problem does not reproduce with sasha's dwarf fixes branch.

Feel free to close this when that is merged with the trunk.
