### ISSUE TITLE
crash in dwarf_dieoffset when processing DWARF

### ISSUE THREAD

**Issue by woodard** [dyninst/dyninst#904]
When processing the symtab for /lib64/libboost_context.so.1.73.0 from boost-context-1.73.0-7.fc33.x86_64
with dyninst trunk at commit 4311e94
run with OMP_NUM_THREADS=1
using this test code
[repo1.C.gz](https://github.com/dyninst/dyninst/files/5461877/repo1.C.gz)

I get the following crash:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7725fe1 in dwarf_dieoffset (die=0x7fffffffb660) at dwarf_dieoffset.c:41
41	  return ((die == NULL || die->cu == NULL)
#0  0x00007ffff7725fe1 in dwarf_dieoffset (die=0x7fffffffb660) at dwarf_dieoffset.c:41
#1  0x00007ffff7f74875 in Dyninst::SymtabAPI::DwarfParseActions::setEntry (e=..., this=0x7fffffffbf30) at /usr/include/c++/10/bits/stl_deque.h:1424
#2  Dyninst::SymtabAPI::DwarfWalker::setEntry (this=0x7fffffffbf30, entry=...) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:2464
#3  0x00007ffff7f7eee4 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf30, e=..., p=false) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:326
#4  0x00007ffff7f80405 in Dyninst::SymtabAPI::DwarfWalker::parseSubprogram (this=0x7fffffffbf30, func_type=<optimized out>) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.h:125
#5  0x00007ffff7f7f32a in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf30, e=..., p=false) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:349
#6  0x00007ffff7f80374 in Dyninst::SymtabAPI::DwarfWalker::parseSubprogram (this=0x7fffffffbf30, func_type=<optimized out>) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.h:130
#7  0x00007ffff7f7f32a in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf30, e=..., p=true) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:349
#8  0x00007ffff7f7f6e1 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf30, e=..., p=true) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:444
#9  0x00007ffff7f7f6e1 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf30, e=..., p=true) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:444
#10 0x00007ffff7f7f6e1 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf30, e=..., p=true) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:444
#11 0x00007ffff7f7f99c in Dyninst::SymtabAPI::DwarfWalker::parseModule (this=0x7fffffffbf30, moduleDIE=..., fixUnknownMod=@0x7fffffffbf18: 0x495d40) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:259
#12 0x00007ffff7f7fd28 in Dyninst::SymtabAPI::DwarfWalker::_ZN7Dyninst9SymtabAPI11DwarfWalker5parseEv._omp_fn.0(void) () at /usr/include/c++/10/bits/stl_vector.h:1043
#13 0x00007ffff75c8d36 in GOMP_parallel (fn=0x7ffff7f7fc00 <Dyninst::SymtabAPI::DwarfWalker::_ZN7Dyninst9SymtabAPI11DwarfWalker5parseEv._omp_fn.0(void)>, data=0x7fffffffc820, num_threads=1, flags=0) at ../../../libgomp/parallel.c:171
#14 0x00007ffff7f7c27e in Dyninst::SymtabAPI::DwarfWalker::parse (this=0x7fffffffc880) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:162
#15 0x00007ffff7f2de31 in Dyninst::SymtabAPI::Object::parseTypeInfo (this=0x480bb0) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/Object-elf.C:4495
#16 0x00007ffff7eda4d9 in Dyninst::SymtabAPI::Symtab::parseTypes (this=0x468780) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/Symtab.C:2164
#17 0x00007ffff7ecc448 in Dyninst::SymtabAPI::FunctionBase::getParams (this=0x49e530, params_=std::vector of length 0, capacity 0) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/Function.C:122
#18 0x000000000040356b in main (argc=<optimized out>, argv=<optimized out>) at repo1.C:64
```
Other libraries that have the same problem:
/lib64/libboost_context.so.1.73.0 from boost-context-1.73.0-7.fc33.x86_64
/lib64/libboost_prg_exec_monitor.so.1.73.0 from boost-test-1.73.0-7.fc33.x86_64
/lib64/libboost_stacktrace_noop.so.1.73.0 from boost-stacktrace-1.73.0-7.fc33.x86_64
/lib64/graphviz/libgvplugin_visio.so.6.0.0 from graphviz-2.44.0-14.fc33.1.x86_64
/lib64/libQt5Help.so.5.15.1 from qt5-qttools-libs-help-5.15.1-1.fc33.x86_64
/lib64/libQt5XcbQpa.so.5.15.1 from qt5-qtbase-gui-5.15.1-5.fc33.x86_64
/lib64/libTKCDF.so.7.4.0 from opencascade-ocaf-7.4.0-5.fc33.x86_64
/lib64/libTKernel.so.7.4.0 from opencascade-foundation-7.4.0-5.fc33.x86_64
/lib64/libTKIVtk.so.7.4.0 from opencascade-visualization-7.4.0-5.fc33.x86_64

**Comment by woodard** [comment]
Verified that this works with the latest dwarf fixes from sasha. 

Feel free to close this once those get merged with the trunk.
