### ISSUE TITLE
Extremely deep recursion resulting in a crash in dwarf_ranges when processing DWARF

### ISSUE THREAD

**Issue by woodard** [dyninst/dyninst#906]
When processing the symtab for /lib64/libproxy.so.1.0.0 from libproxy-0.4.15-25.fc33.x86_64
with dyninst trunk at commit 4311e94
run with OMP_NUM_THREADS=1
using this test code
[repo1.C.gz](https://github.com/dyninst/dyninst/files/5462009/repo1.C.gz)

I get the following crash:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff77252f3 in dwarf_ranges (die=0x7fffff7ff180, offset=0, basep=0x7fffff7ff0f8, startp=0x7fffff7ff100, endp=0x7fffff7ff108) at dwarf_ranges.c:460
460       return 0;
#0  0x00007ffff77252f3 in dwarf_ranges (die=0x7fffff7ff180, offset=0, basep=0x7fffff7ff0f8, startp=0x7fffff7ff100, endp=0x7fffff7ff108) at dwarf_ranges.c:460
#1  0x00007ffff7f7a271 in Dyninst::SymtabAPI::DwarfWalker::getDieRanges (die=...) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:763
#2  0x00007ffff7f7a3ef in Dyninst::SymtabAPI::DwarfWalker::parseRangeTypes (this=0x7fffffffbf40, dbg=0x4adb00, die=...) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:742
#3  0x00007ffff7f8016e in Dyninst::SymtabAPI::DwarfWalker::parseSubprogram (this=0x7fffffffbf40, func_type=Dyninst::SymtabAPI::DwarfWalker::NormalFunc) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.h:120
#4  0x00007ffff7f7f32a in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf40, e=..., p=false) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:349
#5  0x00007ffff7f80374 in Dyninst::SymtabAPI::DwarfWalker::parseSubprogram (this=0x7fffffffbf40, func_type=<optimized out>) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.h:130
#6  0x00007ffff7f7f32a in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf40, e=..., p=false) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:349
<snip>
#38767 0x00007ffff7f80374 in Dyninst::SymtabAPI::DwarfWalker::parseSubprogram (this=0x7fffffffbf40, func_type=<optimized out>) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.h:130
#38768 0x00007ffff7f7f32a in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf40, e=..., p=false) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:349
#38769 0x00007ffff7f80374 in Dyninst::SymtabAPI::DwarfWalker::parseSubprogram (this=0x7fffffffbf40, func_type=<optimized out>) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.h:130
#38770 0x00007ffff7f7f44d in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf40, e=..., p=false) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:352
#38771 0x00007ffff7f80374 in Dyninst::SymtabAPI::DwarfWalker::parseSubprogram (this=0x7fffffffbf40, func_type=<optimized out>) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.h:130
#38772 0x00007ffff7f7f44d in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf40, e=..., p=true) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:352
#38773 0x00007ffff7f7f6e1 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf40, e=..., p=true) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:444
#38774 0x00007ffff7f7f6e1 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf40, e=..., p=true) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:444
#38775 0x00007ffff7f7f6e1 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf40, e=..., p=true) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:444
#38776 0x00007ffff7f7f6e1 in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf40, e=..., p=true) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:444
#38777 0x00007ffff7f7f99c in Dyninst::SymtabAPI::DwarfWalker::parseModule (this=0x7fffffffbf40, moduleDIE=..., fixUnknownMod=@0x7fffffffbf28: 0x4c6cd0) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:259
#38778 0x00007ffff7f7fd28 in Dyninst::SymtabAPI::DwarfWalker::_ZN7Dyninst9SymtabAPI11DwarfWalker5parseEv._omp_fn.0(void) () at /usr/include/c++/10/bits/stl_vector.h:1043
#38779 0x00007ffff75c8d36 in GOMP_parallel (fn=0x7ffff7f7fc00 <Dyninst::SymtabAPI::DwarfWalker::_ZN7Dyninst9SymtabAPI11DwarfWalker5parseEv._omp_fn.0(void)>, data=0x7fffffffc830, num_threads=1, flags=0) at ../../../libgomp/parallel.c:171
#38780 0x00007ffff7f7c27e in Dyninst::SymtabAPI::DwarfWalker::parse (this=0x7fffffffc890) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:162
#38781 0x00007ffff7f2de31 in Dyninst::SymtabAPI::Object::parseTypeInfo (this=0x480bb0) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/Object-elf.C:4495
#38782 0x00007ffff7eda4d9 in Dyninst::SymtabAPI::Symtab::parseTypes (this=0x468780) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/Symtab.C:2164
#38783 0x00007ffff7ecc448 in Dyninst::SymtabAPI::FunctionBase::getParams (this=0x5762d0, params_=std::vector of length 0, capacity 0) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/Function.C:122
#38784 0x000000000040356b in main (argc=<optimized out>, argv=<optimized out>) at repo1.C:64
```

**Comment by woodard** [comment]
Another one that may be the same problem but has a slightly different backtrace is: /lib64/libTKBRep.so.7.4.0 from opencascade-modeling-7.4.0-5.fc33.x86_64

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff771f9eb in __libdw_findabbrev (cu=0x48e718, code=19) at dwarf_tag.c:48
48        abb = Dwarf_Abbrev_Hash_find (&cu->abbrev_hash, code);
#0  0x00007ffff771f9eb in __libdw_findabbrev (cu=0x48e718, code=19) at dwarf_tag.c:48
#1  0x00007ffff7722074 in __libdw_find_attr (die=0x7fffff7ff270, search_name=18, codep=0x7fffff7ff0b0, formp=0x7fffff7ff0b4) at libdwP.h:690
#2  0x00007ffff77203bb in dwarf_attr (die=0x7fffff7ff270, search_name=18, result=0x7fffff7ff0b0) at dwarf_attr.c:45
#3  0x00007ffff77239d2 in dwarf_highpc (die=0x7fffff7ff270, return_addr=0x7fffff7ff1f8) at dwarf_highpc.c:47
#4  0x00007ffff77252f8 in dwarf_ranges (die=0x7fffff7ff270, offset=0, basep=0x7fffff7ff1e8, startp=0x7fffff7ff1f0, endp=0x7fffff7ff1f8) at dwarf_ranges.c:460
#5  0x00007ffff7f7a271 in Dyninst::SymtabAPI::DwarfWalker::getDieRanges (die=...) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:763
#6  0x00007ffff7f7a3ef in Dyninst::SymtabAPI::DwarfWalker::parseRangeTypes (this=0x7fffffffbf40, dbg=0x489370, die=...) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:742
#7  0x00007ffff7f8016e in Dyninst::SymtabAPI::DwarfWalker::parseSubprogram (this=0x7fffffffbf40, func_type=Dyninst::SymtabAPI::DwarfWalker::NormalFunc) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.h:120
#8  0x00007ffff7f7f32a in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf40, e=..., p=false) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:349
#9  0x00007ffff7f80374 in Dyninst::SymtabAPI::DwarfWalker::parseSubprogram (this=0x7fffffffbf40, func_type=<optimized out>) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.h:130
#10 0x00007ffff7f7f32a in Dyninst::SymtabAPI::DwarfWalker::parse_int (this=0x7fffffffbf40, e=..., p=false) at /home/ben/Scratch/Work/dyninst/symtabAPI/src/dwarfWalker.C:349
<snip -- the same as above>
```

**Comment by woodard** [comment]
Verified that this does not happen with the latest dwarf fixes on sasha's branch.

Feel free to close this when those are merged with the trunk.
