### ISSUE TITLE
Error when execution with dyninst

### ISSUE THREAD

**Issue by jordialcaraz** [dyninst/dyninst#940]
**Intention**
What did you want to do?

Install dyninst correctly to run my application which depends on it. I tried to run it, but an error appeared, so I went back to the dyninst examples I had and they didn't work.

**Describe the bug**
When I run an application with dyninst an error appears. It seems to be related to processcreate.
Now abort() in libdwarf. No error argument or handler available.

With gdb --args ./Mutator-counter MiniApp
(gdb)run

(gdb) backtrace
#0  0x00007ffff6a73387 in raise () from /lib64/libc.so.6
#1  0x00007ffff6a74a78 in abort () from /lib64/libc.so.6
#2  0x00007ffff7979ba5 in _dwarf_error (dbg=dbg@entry=0x0, error=<optimized out>,
    errval=errval@entry=104) at ./dwarf_error.c:115
#3  0x00007ffff7990397 in dwarf_dieoffset (die=die@entry=0x7ffffffeb940,
    ret_offset=<optimized out>, error=<optimized out>) at dwarf_query.c:124
#4  0x00007ffff5f945ad in Dyninst::SymtabAPI::Object::dwarf_parse_aranges(Dwarf*, std::set<unsigned long, std::less<unsigned long>, std::allocator<                unsigned long> >&) ()
    at /tmp/jalcaraz/spack-stage/spack-stage-dyninst-10.2.1-j5rxy2pjonovnryzzymvc7yir67zlda3/spack-src/symtabAPI/src/Object-elf.C:2488
#5  0x00007ffff5f94951 in Dyninst::SymtabAPI::Object::fix_global_symbol_modules_static_dwarf() ()
    at /tmp/jalcaraz/spack-stage/spack-stage-dyninst-10.2.1-j5rxy2pjonovnryzzymvc7yir67zlda3/spack-src/symtabAPI/src/Object-elf.C:2517
#6  0x00007ffff5f990e3 in Dyninst::SymtabAPI::Object::load_object(bool) ()
    at /tmp/jalcaraz/spack-stage/spack-stage-dyninst-10.2.1-j5rxy2pjonovnryzzymvc7yir67zlda3/spack-src/symtabAPI/src/Object-elf.C:1610
#7  0x00007ffff5f99e1c in Dyninst::SymtabAPI::Object::Object(MappedFile*, bool, void (*)(char const*), bool, Dyninst::SymtabAPI::Symtab*) ()
    at /tmp/jalcaraz/spack-stage/spack-stage-dyninst-10.2.1-j5rxy2pjonovnryzzymvc7yir67zlda3/spack-src/symtabAPI/src/Object-elf.C:2979
#8  0x00007ffff5f4fd25 in Dyninst::SymtabAPI::Symtab::Symtab(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool,                 bool&) ()
    at /tmp/jalcaraz/spack-stage/spack-stage-dyninst-10.2.1-j5rxy2pjonovnryzzymvc7yir67zlda3/spack-src/symtabAPI/src/Symtab.C:1284
#9  0x00007ffff5f4ff62 in Dyninst::SymtabAPI::Symtab::openFile(Dyninst::SymtabAPI::Symtab*&, std::__cxx11::basic_string<char, std::char_traits<char                >, std::allocator<char> >, Dyninst::SymtabAPI::Symtab::def_t) ()
---Type <return> to continue, or q <return> to quit---q
 at /tmp/jalcaraz/spack-stage/spack-stage-dyninst-10.2.1-j5rxy2pjQuit

**To Reproduce**
Install dyninst with spack.
Script used to install dyninst : https://github.com/jordialcaraz/errors/blob/main/job-spack.sub
Examples used: https://github.com/jordialcaraz/errors/tree/main/Counter-Mutator
Steps to execute the example:
change paths in makefile
make
g++ -g MiniApp.cc -o MiniApp

./Mutator-counter MiniApp

**Expected behavior**
The example executing itself without errors.

**System (please complete the following information):**
 - What platform (x86, x86_64, Power8, Power9, ARMv8)
linux-centos7-sandybridge, x86_64, Xeon E5-2430

**Comment by jordialcaraz** [comment]
I think I found the error, will open this again if after checking with the admin it is not solved.
